// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf7nL8tnVPeJUJTCVUVBgAtIU4yrQWZgw',
    appId: '1:354185618101:web:057627d8829147acbd94fc',
    messagingSenderId: '354185618101',
    projectId: 'bookswap-app-a7f97',
    authDomain: 'bookswap-app-a7f97.firebaseapp.com',
    storageBucket: 'bookswap-app-a7f97.firebasestorage.app',
    measurementId: 'G-QD3F7MQVQ0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1asv-VI9QNGahiPQr3nxCOWcUNRMF9Es',
    appId: '1:354185618101:android:f458d3136f5a2129bd94fc',
    messagingSenderId: '354185618101',
    projectId: 'bookswap-app-a7f97',
    storageBucket: 'bookswap-app-a7f97.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD08As1qj63YemJI2AFt3hv8C733bwjoEo',
    appId: '1:354185618101:ios:ea1f257c1adf22b2bd94fc',
    messagingSenderId: '354185618101',
    projectId: 'bookswap-app-a7f97',
    storageBucket: 'bookswap-app-a7f97.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD08As1qj63YemJI2AFt3hv8C733bwjoEo',
    appId: '1:354185618101:ios:ea1f257c1adf22b2bd94fc',
    messagingSenderId: '354185618101',
    projectId: 'bookswap-app-a7f97',
    storageBucket: 'bookswap-app-a7f97.firebasestorage.app',
    iosBundleId: 'com.example.bookswapApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBf7nL8tnVPeJUJTCVUVBgAtIU4yrQWZgw',
    appId: '1:354185618101:web:bc8ec8763cfbbde8bd94fc',
    messagingSenderId: '354185618101',
    projectId: 'bookswap-app-a7f97',
    authDomain: 'bookswap-app-a7f97.firebaseapp.com',
    storageBucket: 'bookswap-app-a7f97.firebasestorage.app',
    measurementId: 'G-SXWXVQ3NJT',
  );
}
